services:
  #PostgreSQL Database for the application
  tick_tick_boom-postgres:
    image: "postgres:latest"
    container_name: aw-postgres
    #    #Volume mounted for database for the storage
    volumes:
      - ttb-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine
    #Environment variable for DB name, user and password
    environment:
      - POSTGRES_DB=aw
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

#Volumes for DB data
volumes:
  ttb-data:
